# Generated by Django 4.1.7 on 2023-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=26)),
                ('max_problem', models.IntegerField()),
                ('perround_problem', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
