# Generated by Django 4.1.7 on 2023-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='cover_image',
            field=models.ImageField(default='default_image.jpg', upload_to='cover_image/'),
        ),
    ]
