# Generated by Django 4.1.7 on 2023-04-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0003_remove_exercises_cover_image_exercises_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='image',
            field=models.ImageField(blank=True, default=True, upload_to='media/images/exercise_cover_img/'),
        ),
    ]
