# Generated by Django 4.1.7 on 2023-04-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_alter_exercises_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='media/images/exercise_cover_img/'),
        ),
    ]
