# Generated by Django 4.1.7 on 2023-05-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0005_alter_exercises_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='color',
            field=models.CharField(max_length=7, null='#D9D9D9'),
            preserve_default='#D9D9D9',
        ),
    ]
