# Generated by Django 4.1.7 on 2023-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0006_exercises_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
