# Generated by Django 4.1.7 on 2023-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0008_alter_exercises_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
