# Generated by Django 4.1.7 on 2023-09-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0010_shortnote_page_shortnote_color_shortnote_cover_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortnote',
            old_name='cover_img',
            new_name='cover',
        ),
        migrations.RemoveField(
            model_name='shortnote',
            name='color',
        ),
    ]
