# Generated by Django 4.1.7 on 2023-03-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M00A000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.CharField(max_length=60)),
                ('choice1', models.CharField(max_length=30)),
                ('c_id1', models.IntegerField(null=1)),
                ('choice2', models.CharField(max_length=30)),
                ('c_id2', models.IntegerField(null=2)),
                ('choice3', models.CharField(max_length=30)),
                ('c_id3', models.IntegerField(null=3)),
                ('choice4', models.CharField(max_length=30)),
                ('c_id4', models.IntegerField(null=4)),
                ('correct_c_id', models.IntegerField()),
                ('ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general.exercises')),
            ],
        ),
    ]
