# Generated by Django 4.1.7 on 2023-04-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercise', '0002_remove_m00a000_ref_id_m00a000_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='M00A000result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doing_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(null=True)),
                ('problem_text', models.CharField(max_length=60)),
                ('choose', models.IntegerField(null=True)),
                ('correct_c_id', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=2, null=True)),
            ],
        ),
    ]
