# Generated by Django 4.1.7 on 2023-04-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_exercises_cover_image'),
        ('app_exercise', '0004_rename_m00a000result_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='M00A000',
            new_name='exam',
        ),
    ]
