# Generated by Django 4.1.7 on 2023-04-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercise', '0005_rename_m00a000_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='ref_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='ref_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
