# Generated by Django 4.1.7 on 2023-08-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercise', '0024_alter_exam_problem_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='solution',
            field=models.ImageField(blank=True, default=None, upload_to='media/images/solution/'),
        ),
    ]
