# Generated by Django 4.1.7 on 2023-08-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercise', '0025_exam_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='solution',
            new_name='image',
        ),
    ]
