# Generated by Django 4.1.7 on 2023-08-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercise', '0026_rename_solution_exam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(default=None, upload_to='media/images/solution/'),
        ),
    ]
