# Generated by Django 4.1.7 on 2023-08-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercise', '0027_alter_exam_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='image',
            new_name='solution',
        ),
    ]
