# Generated by Django 4.1.7 on 2023-08-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercise', '0028_rename_image_exam_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='solution',
            field=models.ImageField(blank=True, default=None, upload_to='media/images/solution/'),
        ),
    ]
